### NUMPY
O Numpy é uma biblioteca Python usada para trabalhar com matrizes
O Numpy visa fornecer um objeto de matriz que seja até 50x mais rápido do que listas Python tradicionais

#### Array

In [101]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [102]:
#Acessar elementos de um Array
array = np.array([1,2,3,4,5,6])

print(array[2])

3


In [103]:
#Adição de dois elementos de um Array
array = np.array([1,2,3,4,5,6])

print(array[1] + array[3])

6


In [104]:
#Array 2D
array = np.array([[1,2,3,4,5,6], [9,8,7,6,5,4]])

print(array[0,3])

4


In [105]:
array = np.array([[1,2,3,4,5,6], [9,8,7,6,5,4]])

print(array[1,4])

5


In [106]:
array = np.array([[[1,2,3,4,5,6], [9,8,7,6,5,4], [1,3,8,5,8,4]]])

print(array[0,0,2])

3


In [107]:
array = np.array([[1,2,3,4,5,6], [9,8,7,6,5,4]])

print(array[1,-2])

5


In [108]:
#extrair elementos entre dois pontos no indice
array = np.array([1,2,3,4,5])

print(array[1:4])

[2 3 4]


In [109]:
array = np.array([1,2,3,4,5])

print(array[2:])

[3 4 5]


In [110]:
array = np.array([1,2,3,4,5])

print(array[:3])

[1 2 3]


#### Tipo de Dados no Numpy

#### Tipo de Dados em Python
String, integer, float, boolean, complex

#### Tipo de Dados em Numpu

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed shunk of memory for other type (void)


In [111]:
array = np.array([1,2,3,4,5])

print(array.dtype)

int64


In [112]:
array = np.array(['apple', 'banana', 'cherry'])

print(array.dtype)

<U6


In [113]:
array = np.array([1, 2, 3, 4], dtype='f')

print(array)
print(array.dtype)

[1. 2. 3. 4.]
float32


In [114]:
array = np.array([1, 2, 3, 4])
base = array.astype('f')

print(base)
print(base.dtype)

[1. 2. 3. 4.]
float32


#### The Difference Between COPY and VIEW

In [115]:
#COPY, a copy é uma copia do array principal, porém nas inserções de valores eles são independentes

array = np.array([1,2,3,4,5,6])

x = array.copy()
x[0] = 42
array[3] = 32

print(array)
print(x)

[ 1  2  3 32  5  6]
[42  2  3  4  5  6]


In [116]:
#VIEW, a view é uma copia do array principal, porém nas inserções de valores eles são dependentes.
array = np.array([1,2,3,4,5,6])

x = array.view()
x[0] = 42
array[3] = 32

print(array)
print(x)

[42  2  3 32  5  6]
[42  2  3 32  5  6]


#### SHAPE

In [117]:
array = np.array([[1,2,3,4,5,6], [9,8,7,6,5,4]])

print(array.shape)

(2, 6)


In [118]:
array = np.array([1,2,3,4,5,6], ndmin= 2 )

print(array)
print(array.shape)

[[1 2 3 4 5 6]]
(1, 6)


#### RESHAPE

Também existem outras funções para remodelar arrays(flatten, ravel, rot90, flip, fliplr, flipud)

In [119]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [120]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [121]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array.reshape(2,6).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [122]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array.reshape(2,2,-1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [123]:
array = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(array.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [124]:
array = np.array([[1,2,3,4,5,6],[9,2,3,5,4,6]])

for x in array:
    print(x, x)

[1 2 3 4 5 6] [1 2 3 4 5 6]
[9 2 3 5 4 6] [9 2 3 5 4 6]


In [125]:
array = np.array([[1,2,3,4,5,6],[9,2,3,5,4,6]])

for x in array:
    for y in x:
        print(y)

1
2
3
4
5
6
9
2
3
5
4
6


In [126]:
array = np.array([[1,2,3,4], [2,3,4,5], [1,2,3,5]])

for x in np.nditer(array):
    print(x)

#print(array)

1
2
3
4
2
3
4
5
1
2
3
5


In [127]:
array = np.array([1,2,3,4])

for x in np.nditer(array, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [128]:
array = np.array([[1,2,3,4,5],[1,2,3,4,7]])

for x in np.nditer(array[:,::2]):
    print(x)

1
3
5
1
3
7


In [129]:
array = np.array([1,2,3,4,5])

for idx, x in np.ndenumerate(array):
    print(idx, x)


(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [130]:
array = np.array([[1,2,3,4,5],[9,5,8,7,6]])

for idx, x in np.ndenumerate(array):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 9
(1, 1) 5
(1, 2) 8
(1, 3) 7
(1, 4) 6


#### CONCATENATE()

Junção de arrays

In [131]:
array1 = np.array([1,2,3,4])
array2 = np.array([34,2,1,2])


base = np.concatenate((array1, array2))

print(base)

[ 1  2  3  4 34  2  1  2]


In [132]:
array1 = np.array([[1,2,3,4], [2,3,5,6]])
array2 = np.array([[34,2,1,2], [2,3,5,6]])


base = np.concatenate((array1, array2), axis=1)

print(base)

[[ 1  2  3  4 34  2  1  2]
 [ 2  3  5  6  2  3  5  6]]


#### STACK()

In [137]:
# Unindo matrizes com função de pilha
array1 = np.array([[1,2,3,4], [2,3,5,6]])
array2 = np.array([[34,2,1,2], [2,3,5,6]])


base = np.stack((array1, array2), axis=1)

print(base)

[[[ 1  2  3  4]
  [34  2  1  2]]

 [[ 2  3  5  6]
  [ 2  3  5  6]]]


#### HSTACK, VSTACK, DSTACK

In [136]:
#Empilando por linhas
array1 = np.array([[1,2,3,4], [2,3,5,6]])
array2 = np.array([[34,2,1,2], [2,3,5,6]])


base = np.hstack((array1, array2))

print(base)

[[ 1  2  3  4 34  2  1  2]
 [ 2  3  5  6  2  3  5  6]]


In [138]:
# Empilhando por colunas
array1 = np.array([[1,2,3,4], [2,3,5,6]])
array2 = np.array([[34,2,1,2], [2,3,5,6]])


base = np.vstack((array1, array2))

print(base)

[[ 1  2  3  4]
 [ 2  3  5  6]
 [34  2  1  2]
 [ 2  3  5  6]]


In [140]:
# Empilhando ao longo da altura(profundidade)
array1 = np.array([[1,2,3,4], [2,3,5,6]])
array2 = np.array([[34,2,1,2], [2,3,5,6]])


base = np.dstack((array1, array2))

print(base)

[[[ 1 34]
  [ 2  2]
  [ 3  1]
  [ 4  2]]

 [[ 2  2]
  [ 3  3]
  [ 5  5]
  [ 6  6]]]


#### DIVIDINDO ARRAYS COM NUMPY

#### ARRAY_SPLIT()

In [142]:
array = np.array([1,2,3,4,5,6,7,8])

base = np.array_split(array,3)

print(base)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [143]:
array = np.array([1,2,3,4,5,6,7,8])

base = np.array_split(array,3)

print(base[0])
print(base[1])
print(base[2])

[1 2 3]
[4 5 6]
[7 8]


In [147]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

base = np.array_split(array,3)

print(base)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [148]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

base = np.array_split(array,3, axis=1)

print(base)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [157]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

base = np.hsplit(array,3)

print(base)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [158]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

base = np.vsplit(array,3)

print(base)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


#### Pesquisando arrays

#### WHERE() e SEARCHSORTED()

In [169]:
array = np.array([1,2,3,4,5,6,4,4])

x = np.where(array == 4)

print(x)

(array([3, 6, 7]),)


In [170]:
array = np.array([1,2,3,4,5,6,4,4])

x = np.where(array%2 == 0)

print(x)

(array([1, 3, 5, 6, 7]),)


In [171]:
array = np.array([1,2,3,4,5,6,4,4])

x = np.where(array%2 == 1)

print(x)

(array([0, 2, 4]),)


#### SEARCHSORTED

In [174]:
array = np.array([1,2,3,4,5,6,4,4])

x = np.searchsorted(array, 4)

print(x)

3


In [182]:
array = np.array([1,2,3,4,5,6,4,4,5])

x = np.searchsorted(array, 6, side='right')

print(x)

9


#### Classificação de Matrizes
Sequencia Ordenada com sort()

In [186]:
import numpy as np

array = np.array([3,5,1,2,9])

print(np.sort(array))

[1 2 3 5 9]


In [187]:
array = np.array(["bola", "avião", "faca"])

print(np.sort(array))

['avião' 'bola' 'faca']


In [188]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#### Filtrando Matrizes

In [189]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [190]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [191]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [192]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [193]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
